import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

const lexend = localFont({
  src: "./fonts/Lexend-VariableFont_wght.ttf",
  variable: "--font-lexend",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={`${lexend.variable} ${lexend.variable} antialiased`}>
          <div className=" grid grid-rows-[auto_1fr] h-screen px-primary gap-5">
            {children}
          </div>
        </body>
      </UserProvider>
    </html>
  );
}
